// ----------------------------------------------------------------------------
// <auto-generated>
// This is autogenerated code by CppSharp.
// Do not edit this file or all your changes will be lost after re-generation.
// </auto-generated>
// ----------------------------------------------------------------------------

export enum ErrorCode {
  BUFFER_SIZE_QUERY = -1,
  SUCCESS = 0,
  OBJECT_NOT_RESOLVED = 1,
  RULESET_UNAVAILABLE = 2,
  UNEXPECTED_RULESET = 3,
  FAILURE = 127,
}

export class ManagedObjectHandle {
  constructor();

  constructor(_0: ManagedObjectHandle);

  id: number;
}

export class NativeBeatmap {
  constructor();

  constructor(_0: NativeBeatmap);

  handle: ManagedObjectHandle;
  rulesetId: number;
  beatmapId: number;
  approachRate: number;
  drainRate: number;
  overallDifficulty: number;
  circleSize: number;
  sliderMultiplier: number;
  sliderTickRate: number;
}

export class NativeMod {
  constructor();

  constructor(_0: NativeMod);

  handle: ManagedObjectHandle;
}

export class NativeModsCollection {
  constructor();

  constructor(_0: NativeModsCollection);

  handle: ManagedObjectHandle;
}

export class NativeRuleset {
  constructor();

  constructor(_0: NativeRuleset);

  handle: ManagedObjectHandle;
  rulesetId: number;
}

export class Cabinet__Nullable_int64_t {
  constructor();

  constructor(_0: Cabinet__Nullable_int64_t);

  hasValue: boolean;
  value: number;
}

export class NativeScoreInfo {
  constructor();

  constructor(_0: NativeScoreInfo);

  rulesetHandle: ManagedObjectHandle;
  beatmapHandle: ManagedObjectHandle;
  modsHandle: ManagedObjectHandle;
  maxCombo: number;
  accuracy: number;
  legacyTotalScore: Cabinet__Nullable_int64_t;
  countMiss: number;
  countMeh: number;
  countOk: number;
  countGood: number;
  countGreat: number;
  countPerfect: number;
  countSliderTailHit: number;
  countLargeTickMiss: number;
}

export class NativeCatchPerformanceAttributes {
  constructor();

  constructor(_0: NativeCatchPerformanceAttributes);

  total: number;
}

export class NativeCatchPerformanceCalculator {
  constructor();

  constructor(_0: NativeCatchPerformanceCalculator);

  handle: ManagedObjectHandle;
}

export class NativeManiaPerformanceAttributes {
  constructor();

  constructor(_0: NativeManiaPerformanceAttributes);

  total: number;
  difficulty: number;
}

export class NativeManiaPerformanceCalculator {
  constructor();

  constructor(_0: NativeManiaPerformanceCalculator);

  handle: ManagedObjectHandle;
}

export class Cabinet__Nullable_double {
  constructor();

  constructor(_0: Cabinet__Nullable_double);

  hasValue: boolean;
  value: number;
}

export class NativeOsuPerformanceAttributes {
  constructor();

  constructor(_0: NativeOsuPerformanceAttributes);

  total: number;
  aim: number;
  speed: number;
  accuracy: number;
  flashlight: number;
  effectiveMissCount: number;
  speedDeviation: Cabinet__Nullable_double;
  comboBasedEstimatedMissCount: number;
  scoreBasedEstimatedMissCount: Cabinet__Nullable_double;
  aimEstimatedSliderBreaks: number;
  speedEstimatedSliderBreaks: number;
}

export class NativeOsuPerformanceCalculator {
  constructor();

  constructor(_0: NativeOsuPerformanceCalculator);

  handle: ManagedObjectHandle;
}

export class NativeTaikoPerformanceAttributes {
  constructor();

  constructor(_0: NativeTaikoPerformanceAttributes);

  total: number;
  difficulty: number;
  accuracy: number;
  estimatedUnstableRate: Cabinet__Nullable_double;
}

export class NativeTaikoPerformanceCalculator {
  constructor();

  constructor(_0: NativeTaikoPerformanceCalculator);

  handle: ManagedObjectHandle;
}

export class NativeCatchDifficultyAttributes {
  constructor();

  constructor(_0: NativeCatchDifficultyAttributes);

  starRating: number;
  maxCombo: number;
}

export class NativeCatchDifficultyCalculator {
  constructor();

  constructor(_0: NativeCatchDifficultyCalculator);

  handle: ManagedObjectHandle;
}

export class NativeManiaDifficultyAttributes {
  constructor();

  constructor(_0: NativeManiaDifficultyAttributes);

  starRating: number;
  maxCombo: number;
}

export class NativeManiaDifficultyCalculator {
  constructor();

  constructor(_0: NativeManiaDifficultyCalculator);

  handle: ManagedObjectHandle;
}

export class NativeOsuDifficultyAttributes {
  constructor();

  constructor(_0: NativeOsuDifficultyAttributes);

  starRating: number;
  maxCombo: number;
  aimDifficulty: number;
  aimDifficultSliderCount: number;
  speedDifficulty: number;
  speedNoteCount: number;
  flashlightDifficulty: number;
  sliderFactor: number;
  aimTopWeightedSliderFactor: number;
  speedTopWeightedSliderFactor: number;
  aimDifficultStrainCount: number;
  speedDifficultStrainCount: number;
  nestedScorePerObject: number;
  legacyScoreBaseMultiplier: number;
  maximumLegacyComboScore: number;
  drainRate: number;
  hitCircleCount: number;
  sliderCount: number;
  spinnerCount: number;
}

export class NativeOsuDifficultyCalculator {
  constructor();

  constructor(_0: NativeOsuDifficultyCalculator);

  handle: ManagedObjectHandle;
}

export class NativeTaikoDifficultyAttributes {
  constructor();

  constructor(_0: NativeTaikoDifficultyAttributes);

  starRating: number;
  maxCombo: number;
  mechanicalDifficulty: number;
  rhythmDifficulty: number;
  readingDifficulty: number;
  colourDifficulty: number;
  staminaDifficulty: number;
  monoStaminaFactor: number;
  consistencyFactor: number;
  staminaTopStrains: number;
}

export class NativeTaikoDifficultyCalculator {
  constructor();

  constructor(_0: NativeTaikoDifficultyCalculator);

  handle: ManagedObjectHandle;
}

export class NativeTimedCatchDifficultyAttributes {
  constructor();

  constructor(_0: NativeTimedCatchDifficultyAttributes);

  time: number;
  attributes: NativeCatchDifficultyAttributes;
}

export class NativeTimedManiaDifficultyAttributes {
  constructor();

  constructor(_0: NativeTimedManiaDifficultyAttributes);

  time: number;
  attributes: NativeManiaDifficultyAttributes;
}

export class NativeTimedOsuDifficultyAttributes {
  constructor();

  constructor(_0: NativeTimedOsuDifficultyAttributes);

  time: number;
  attributes: NativeOsuDifficultyAttributes;
}

export class NativeTimedTaikoDifficultyAttributes {
  constructor();

  constructor(_0: NativeTimedTaikoDifficultyAttributes);

  time: number;
  attributes: NativeTaikoDifficultyAttributes;
}

export function ErrorHandler_GetLastMessage(): string;
export function Beatmap_CreateFromFile(
  filePathPtr: null | Buffer | string,
  nativeBeatmapPtr: NativeBeatmap,
): ErrorCode;
export function Beatmap_CreateFromText(
  beatmapTextPtr: null | Buffer | string,
  nativeBeatmapPtr: NativeBeatmap,
): ErrorCode;
export function Beatmap_GetTitle(
  beatmapHandle: ManagedObjectHandle,
  buffer: null | Buffer | string,
  bufferSize: Int32Array,
): ErrorCode;
export function Beatmap_GetArtist(
  beatmapHandle: ManagedObjectHandle,
  buffer: null | Buffer | string,
  bufferSize: Int32Array,
): ErrorCode;
export function Beatmap_GetVersion(
  beatmapHandle: ManagedObjectHandle,
  buffer: null | Buffer | string,
  bufferSize: Int32Array,
): ErrorCode;
export function Beatmap_Destroy(handle: ManagedObjectHandle): ErrorCode;
export function Mod_Create(
  acronymPtr: null | Buffer | string,
  nativeModPtr: NativeMod,
): ErrorCode;
export function Mod_SetSettingBool(
  modHandle: ManagedObjectHandle,
  keyPtr: null | Buffer | string,
  value: boolean,
): ErrorCode;
export function Mod_SetSettingInteger(
  modHandle: ManagedObjectHandle,
  keyPtr: null | Buffer | string,
  value: number,
): ErrorCode;
export function Mod_SetSettingFloat(
  modHandle: ManagedObjectHandle,
  keyPtr: null | Buffer | string,
  value: number,
): ErrorCode;
export function Mod_Debug(modHandle: ManagedObjectHandle): ErrorCode;
export function Mod_Destroy(handle: ManagedObjectHandle): ErrorCode;
export function ModsCollection_Create(
  nativeModsCollectionPtr: NativeModsCollection,
): ErrorCode;
export function ModsCollection_Add(
  modsCollectionHandle: ManagedObjectHandle,
  modHandle: ManagedObjectHandle,
): ErrorCode;
export function ModsCollection_Remove(
  modsCollectionHandle: ManagedObjectHandle,
  modHandle: ManagedObjectHandle,
): ErrorCode;
export function ModsCollection_Debug(
  modsCollectionHandle: ManagedObjectHandle,
): ErrorCode;
export function ModsCollection_Destroy(handle: ManagedObjectHandle): ErrorCode;
export function Ruleset_CreateFromId(
  rulesetId: number,
  rulesetPtr: NativeRuleset,
): ErrorCode;
export function Ruleset_CreateFromShortName(
  shortName: null | Buffer | string,
  rulesetPtr: NativeRuleset,
): ErrorCode;
export function Ruleset_GetShortName(
  rulesetHandle: ManagedObjectHandle,
  buffer: null | Buffer | string,
  bufferSize: Int32Array,
): ErrorCode;
export function Ruleset_Destroy(handle: ManagedObjectHandle): ErrorCode;
export function CatchPerformanceCalculator_Create(
  nativeCatchPerformanceCalculatorPtr: NativeCatchPerformanceCalculator,
): ErrorCode;
export function CatchPerformanceCalculator_Calculate(
  calcHandle: ManagedObjectHandle,
  nativeScoreInfo: NativeScoreInfo,
  nativeDifficultyAttributes: NativeCatchDifficultyAttributes,
  nativeAttributesPtr: NativeCatchPerformanceAttributes,
): ErrorCode;
export function CatchPerformanceCalculator_Destroy(
  handle: ManagedObjectHandle,
): ErrorCode;
export function ManiaPerformanceCalculator_Create(
  nativeManiaPerformanceCalculatorPtr: NativeManiaPerformanceCalculator,
): ErrorCode;
export function ManiaPerformanceCalculator_Calculate(
  calcHandle: ManagedObjectHandle,
  nativeScoreInfo: NativeScoreInfo,
  nativeDifficultyAttributes: NativeManiaDifficultyAttributes,
  nativeAttributesPtr: NativeManiaPerformanceAttributes,
): ErrorCode;
export function ManiaPerformanceCalculator_Destroy(
  handle: ManagedObjectHandle,
): ErrorCode;
export function OsuPerformanceCalculator_Create(
  nativeOsuPerformanceCalculatorPtr: NativeOsuPerformanceCalculator,
): ErrorCode;
export function OsuPerformanceCalculator_Calculate(
  calcHandle: ManagedObjectHandle,
  nativeScoreInfo: NativeScoreInfo,
  nativeDifficultyAttributes: NativeOsuDifficultyAttributes,
  nativeAttributesPtr: NativeOsuPerformanceAttributes,
): ErrorCode;
export function OsuPerformanceCalculator_Destroy(
  handle: ManagedObjectHandle,
): ErrorCode;
export function TaikoPerformanceCalculator_Create(
  nativeTaikoPerformanceCalculatorPtr: NativeTaikoPerformanceCalculator,
): ErrorCode;
export function TaikoPerformanceCalculator_Calculate(
  calcHandle: ManagedObjectHandle,
  nativeScoreInfo: NativeScoreInfo,
  nativeDifficultyAttributes: NativeTaikoDifficultyAttributes,
  nativeAttributesPtr: NativeTaikoPerformanceAttributes,
): ErrorCode;
export function TaikoPerformanceCalculator_Destroy(
  handle: ManagedObjectHandle,
): ErrorCode;
export function CatchDifficultyCalculator_Create(
  rulesetHandle: ManagedObjectHandle,
  beatmapHandle: ManagedObjectHandle,
  nativeCatchDifficultyCalculatorPtr: NativeCatchDifficultyCalculator,
): ErrorCode;
export function CatchDifficultyCalculator_Calculate(
  calcHandle: ManagedObjectHandle,
  nativeAttributesPtr: NativeCatchDifficultyAttributes,
): ErrorCode;
export function CatchDifficultyCalculator_CalculateMods(
  calcHandle: ManagedObjectHandle,
  modsHandle: ManagedObjectHandle,
  nativeAttributesPtr: NativeCatchDifficultyAttributes,
): ErrorCode;
export function CatchDifficultyCalculator_CalculateTimed(
  calcHandle: ManagedObjectHandle,
  nativeTimedAttributesBuffer: null | NativeTimedCatchDifficultyAttributes[],
  bufferSize: Int32Array,
): ErrorCode;
export function CatchDifficultyCalculator_CalculateModsTimed(
  calcHandle: ManagedObjectHandle,
  modsHandle: ManagedObjectHandle,
  nativeTimedAttributesBuffer: null | NativeTimedCatchDifficultyAttributes[],
  bufferSize: Int32Array,
): ErrorCode;
export function CatchDifficultyCalculator_Destroy(
  handle: ManagedObjectHandle,
): ErrorCode;
export function ManiaDifficultyCalculator_Create(
  rulesetHandle: ManagedObjectHandle,
  beatmapHandle: ManagedObjectHandle,
  nativeManiaDifficultyCalculatorPtr: NativeManiaDifficultyCalculator,
): ErrorCode;
export function ManiaDifficultyCalculator_Calculate(
  calcHandle: ManagedObjectHandle,
  nativeAttributesPtr: NativeManiaDifficultyAttributes,
): ErrorCode;
export function ManiaDifficultyCalculator_CalculateMods(
  calcHandle: ManagedObjectHandle,
  modsHandle: ManagedObjectHandle,
  nativeAttributesPtr: NativeManiaDifficultyAttributes,
): ErrorCode;
export function ManiaDifficultyCalculator_CalculateTimed(
  calcHandle: ManagedObjectHandle,
  nativeTimedAttributesBuffer: null | NativeTimedManiaDifficultyAttributes[],
  bufferSize: Int32Array,
): ErrorCode;
export function ManiaDifficultyCalculator_CalculateModsTimed(
  calcHandle: ManagedObjectHandle,
  modsHandle: ManagedObjectHandle,
  nativeTimedAttributesBuffer: null | NativeTimedManiaDifficultyAttributes[],
  bufferSize: Int32Array,
): ErrorCode;
export function ManiaDifficultyCalculator_Destroy(
  handle: ManagedObjectHandle,
): ErrorCode;
export function OsuDifficultyCalculator_Create(
  rulesetHandle: ManagedObjectHandle,
  beatmapHandle: ManagedObjectHandle,
  nativeOsuDifficultyCalculatorPtr: NativeOsuDifficultyCalculator,
): ErrorCode;
export function OsuDifficultyCalculator_Calculate(
  calcHandle: ManagedObjectHandle,
  nativeAttributesPtr: NativeOsuDifficultyAttributes,
): ErrorCode;
export function OsuDifficultyCalculator_CalculateMods(
  calcHandle: ManagedObjectHandle,
  modsHandle: ManagedObjectHandle,
  nativeAttributesPtr: NativeOsuDifficultyAttributes,
): ErrorCode;
export function OsuDifficultyCalculator_CalculateTimed(
  calcHandle: ManagedObjectHandle,
  nativeTimedAttributesBuffer: null | NativeTimedOsuDifficultyAttributes[],
  bufferSize: Int32Array,
): ErrorCode;
export function OsuDifficultyCalculator_CalculateModsTimed(
  calcHandle: ManagedObjectHandle,
  modsHandle: ManagedObjectHandle,
  nativeTimedAttributesBuffer: null | NativeTimedOsuDifficultyAttributes[],
  bufferSize: Int32Array,
): ErrorCode;
export function OsuDifficultyCalculator_Destroy(
  handle: ManagedObjectHandle,
): ErrorCode;
export function TaikoDifficultyCalculator_Create(
  rulesetHandle: ManagedObjectHandle,
  beatmapHandle: ManagedObjectHandle,
  nativeTaikoDifficultyCalculatorPtr: NativeTaikoDifficultyCalculator,
): ErrorCode;
export function TaikoDifficultyCalculator_Calculate(
  calcHandle: ManagedObjectHandle,
  nativeAttributesPtr: NativeTaikoDifficultyAttributes,
): ErrorCode;
export function TaikoDifficultyCalculator_CalculateMods(
  calcHandle: ManagedObjectHandle,
  modsHandle: ManagedObjectHandle,
  nativeAttributesPtr: NativeTaikoDifficultyAttributes,
): ErrorCode;
export function TaikoDifficultyCalculator_CalculateTimed(
  calcHandle: ManagedObjectHandle,
  nativeTimedAttributesBuffer: null | NativeTimedTaikoDifficultyAttributes[],
  bufferSize: Int32Array,
): ErrorCode;
export function TaikoDifficultyCalculator_CalculateModsTimed(
  calcHandle: ManagedObjectHandle,
  modsHandle: ManagedObjectHandle,
  nativeTimedAttributesBuffer: null | NativeTimedTaikoDifficultyAttributes[],
  bufferSize: Int32Array,
): ErrorCode;
export function TaikoDifficultyCalculator_Destroy(
  handle: ManagedObjectHandle,
): ErrorCode;
