// -- Generated by Cabinet 0.0.6
// -- https://github.com/minisbett/cabinet
//
// Assembly: F:\coding\pr-check\osu-native\Artifacts\bin\osu.Native\release\osu.Native.dll
//     Date: 2026-02-11 20:17:08 +03:00

#include <stdint.h>
#include <stdbool.h>

typedef enum ErrorCode
{
    END_OF_ENUMERATION = -2,
    BUFFER_SIZE_QUERY = -1,
    SUCCESS = 0,
    OBJECT_NOT_RESOLVED = 1,
    RULESET_UNAVAILABLE = 2,
    UNEXPECTED_RULESET = 3,
    FAILURE = 127
} ErrorCode;

typedef struct ManagedObjectHandle
{
    uint32_t id;
} ManagedObjectHandle;

typedef struct NativeBeatmap
{
    ManagedObjectHandle handle;
    int32_t rulesetId;
    int32_t beatmapId;
    float approachRate;
    float drainRate;
    float overallDifficulty;
    float circleSize;
    double sliderMultiplier;
    double sliderTickRate;
} NativeBeatmap;

typedef struct NativeMod
{
    ManagedObjectHandle handle;
} NativeMod;

typedef struct NativeModsCollection
{
    ManagedObjectHandle handle;
} NativeModsCollection;

typedef struct NativeRuleset
{
    ManagedObjectHandle handle;
    int32_t rulesetId;
} NativeRuleset;

typedef struct Cabinet__Nullable_int64_t
{
    bool hasValue;
    int64_t value;
} Cabinet__Nullable_int64_t;

typedef struct NativeScoreInfo
{
    ManagedObjectHandle rulesetHandle;
    ManagedObjectHandle beatmapHandle;
    ManagedObjectHandle modsHandle;
    int32_t maxCombo;
    double accuracy;
    Cabinet__Nullable_int64_t legacyTotalScore;
    int32_t countMiss;
    int32_t countMeh;
    int32_t countOk;
    int32_t countGood;
    int32_t countGreat;
    int32_t countPerfect;
    int32_t countSliderTailHit;
    int32_t countLargeTickMiss;
} NativeScoreInfo;

typedef struct NativeCatchPerformanceAttributes
{
    double total;
} NativeCatchPerformanceAttributes;

typedef struct NativeCatchPerformanceCalculator
{
    ManagedObjectHandle handle;
} NativeCatchPerformanceCalculator;

typedef struct NativeManiaPerformanceAttributes
{
    double total;
    double difficulty;
} NativeManiaPerformanceAttributes;

typedef struct NativeManiaPerformanceCalculator
{
    ManagedObjectHandle handle;
} NativeManiaPerformanceCalculator;

typedef struct Cabinet__Nullable_double
{
    bool hasValue;
    double value;
} Cabinet__Nullable_double;

typedef struct NativeOsuPerformanceAttributes
{
    double total;
    double aim;
    double speed;
    double accuracy;
    double flashlight;
    double effectiveMissCount;
    Cabinet__Nullable_double speedDeviation;
    double comboBasedEstimatedMissCount;
    Cabinet__Nullable_double scoreBasedEstimatedMissCount;
    double aimEstimatedSliderBreaks;
    double speedEstimatedSliderBreaks;
} NativeOsuPerformanceAttributes;

typedef struct NativeOsuPerformanceCalculator
{
    ManagedObjectHandle handle;
} NativeOsuPerformanceCalculator;

typedef struct NativeTaikoPerformanceAttributes
{
    double total;
    double difficulty;
    double accuracy;
    Cabinet__Nullable_double estimatedUnstableRate;
} NativeTaikoPerformanceAttributes;

typedef struct NativeTaikoPerformanceCalculator
{
    ManagedObjectHandle handle;
} NativeTaikoPerformanceCalculator;

typedef struct NativeCatchDifficultyAttributes
{
    double starRating;
    int32_t maxCombo;
} NativeCatchDifficultyAttributes;

typedef struct NativeCatchDifficultyCalculator
{
    ManagedObjectHandle handle;
} NativeCatchDifficultyCalculator;

typedef struct NativeManiaDifficultyAttributes
{
    double starRating;
    int32_t maxCombo;
} NativeManiaDifficultyAttributes;

typedef struct NativeManiaDifficultyCalculator
{
    ManagedObjectHandle handle;
} NativeManiaDifficultyCalculator;

typedef struct NativeOsuDifficultyAttributes
{
    double starRating;
    int32_t maxCombo;
    double aimDifficulty;
    double aimDifficultSliderCount;
    double speedDifficulty;
    double speedNoteCount;
    double flashlightDifficulty;
    double sliderFactor;
    double aimTopWeightedSliderFactor;
    double speedTopWeightedSliderFactor;
    double aimDifficultStrainCount;
    double speedDifficultStrainCount;
    double nestedScorePerObject;
    double legacyScoreBaseMultiplier;
    double maximumLegacyComboScore;
    double drainRate;
    int32_t hitCircleCount;
    int32_t sliderCount;
    int32_t spinnerCount;
} NativeOsuDifficultyAttributes;

typedef struct NativeOsuDifficultyCalculator
{
    ManagedObjectHandle handle;
} NativeOsuDifficultyCalculator;

typedef struct NativeTaikoDifficultyAttributes
{
    double starRating;
    int32_t maxCombo;
    double mechanicalDifficulty;
    double rhythmDifficulty;
    double readingDifficulty;
    double colourDifficulty;
    double staminaDifficulty;
    double monoStaminaFactor;
    double consistencyFactor;
    double staminaTopStrains;
} NativeTaikoDifficultyAttributes;

typedef struct NativeTaikoDifficultyCalculator
{
    ManagedObjectHandle handle;
} NativeTaikoDifficultyCalculator;

typedef struct NativeTimedCatchDifficultyAttributes
{
    double time;
    NativeCatchDifficultyAttributes attributes;
} NativeTimedCatchDifficultyAttributes;

typedef struct NativeTimedManiaDifficultyAttributes
{
    double time;
    NativeManiaDifficultyAttributes attributes;
} NativeTimedManiaDifficultyAttributes;

typedef struct NativeTimedOsuDifficultyAttributes
{
    double time;
    NativeOsuDifficultyAttributes attributes;
} NativeTimedOsuDifficultyAttributes;

typedef struct NativeTimedTaikoDifficultyAttributes
{
    double time;
    NativeTaikoDifficultyAttributes attributes;
} NativeTimedTaikoDifficultyAttributes;


extern "C" {

const char* ErrorHandler_GetLastMessage();
const ErrorCode Beatmap_CreateFromFile(uint8_t* filePathPtr, NativeBeatmap* nativeBeatmapPtr);
const ErrorCode Beatmap_CreateFromText(uint8_t* beatmapTextPtr, NativeBeatmap* nativeBeatmapPtr);
const ErrorCode Beatmap_GetTitle(ManagedObjectHandle beatmapHandle, uint8_t* buffer, int32_t* bufferSize);
const ErrorCode Beatmap_GetArtist(ManagedObjectHandle beatmapHandle, uint8_t* buffer, int32_t* bufferSize);
const ErrorCode Beatmap_GetVersion(ManagedObjectHandle beatmapHandle, uint8_t* buffer, int32_t* bufferSize);
const ErrorCode Beatmap_Destroy(ManagedObjectHandle handle);
const ErrorCode Mod_Create(uint8_t* acronymPtr, NativeMod* nativeModPtr);
const ErrorCode Mod_SetSettingBool(ManagedObjectHandle modHandle, uint8_t* keyPtr, bool value);
const ErrorCode Mod_SetSettingInteger(ManagedObjectHandle modHandle, uint8_t* keyPtr, int32_t value);
const ErrorCode Mod_SetSettingFloat(ManagedObjectHandle modHandle, uint8_t* keyPtr, float value);
const ErrorCode Mod_Debug(ManagedObjectHandle modHandle);
const ErrorCode Mod_Destroy(ManagedObjectHandle handle);
const ErrorCode ModsCollection_Create(NativeModsCollection* nativeModsCollectionPtr);
const ErrorCode ModsCollection_Add(ManagedObjectHandle modsCollectionHandle, ManagedObjectHandle modHandle);
const ErrorCode ModsCollection_Remove(ManagedObjectHandle modsCollectionHandle, ManagedObjectHandle modHandle);
const ErrorCode ModsCollection_Debug(ManagedObjectHandle modsCollectionHandle);
const ErrorCode ModsCollection_Destroy(ManagedObjectHandle handle);
const ErrorCode Ruleset_CreateFromId(int32_t rulesetId, NativeRuleset* rulesetPtr);
const ErrorCode Ruleset_CreateFromShortName(uint8_t* shortName, NativeRuleset* rulesetPtr);
const ErrorCode Ruleset_GetShortName(ManagedObjectHandle rulesetHandle, uint8_t* buffer, int32_t* bufferSize);
const ErrorCode Ruleset_Destroy(ManagedObjectHandle handle);
const ErrorCode CatchPerformanceCalculator_Create(NativeCatchPerformanceCalculator* nativeCatchPerformanceCalculatorPtr);
const ErrorCode CatchPerformanceCalculator_Calculate(ManagedObjectHandle calcHandle, NativeScoreInfo nativeScoreInfo, NativeCatchDifficultyAttributes nativeDifficultyAttributes, NativeCatchPerformanceAttributes* nativeAttributesPtr);
const ErrorCode CatchPerformanceCalculator_Destroy(ManagedObjectHandle handle);
const ErrorCode ManiaPerformanceCalculator_Create(NativeManiaPerformanceCalculator* nativeManiaPerformanceCalculatorPtr);
const ErrorCode ManiaPerformanceCalculator_Calculate(ManagedObjectHandle calcHandle, NativeScoreInfo nativeScoreInfo, NativeManiaDifficultyAttributes nativeDifficultyAttributes, NativeManiaPerformanceAttributes* nativeAttributesPtr);
const ErrorCode ManiaPerformanceCalculator_Destroy(ManagedObjectHandle handle);
const ErrorCode OsuPerformanceCalculator_Create(NativeOsuPerformanceCalculator* nativeOsuPerformanceCalculatorPtr);
const ErrorCode OsuPerformanceCalculator_Calculate(ManagedObjectHandle calcHandle, NativeScoreInfo nativeScoreInfo, NativeOsuDifficultyAttributes nativeDifficultyAttributes, NativeOsuPerformanceAttributes* nativeAttributesPtr);
const ErrorCode OsuPerformanceCalculator_Destroy(ManagedObjectHandle handle);
const ErrorCode TaikoPerformanceCalculator_Create(NativeTaikoPerformanceCalculator* nativeTaikoPerformanceCalculatorPtr);
const ErrorCode TaikoPerformanceCalculator_Calculate(ManagedObjectHandle calcHandle, NativeScoreInfo nativeScoreInfo, NativeTaikoDifficultyAttributes nativeDifficultyAttributes, NativeTaikoPerformanceAttributes* nativeAttributesPtr);
const ErrorCode TaikoPerformanceCalculator_Destroy(ManagedObjectHandle handle);
const ErrorCode CatchDifficultyCalculator_Create(ManagedObjectHandle rulesetHandle, ManagedObjectHandle beatmapHandle, NativeCatchDifficultyCalculator* nativeCatchDifficultyCalculatorPtr);
const ErrorCode CatchDifficultyCalculator_Calculate(ManagedObjectHandle calcHandle, ManagedObjectHandle modsHandle, NativeCatchDifficultyAttributes* nativeAttributesPtr);
const ErrorCode CatchDifficultyCalculator_CalculateTimed(ManagedObjectHandle calcHandle, ManagedObjectHandle modsHandle, NativeTimedCatchDifficultyAttributes* nativeTimedAttributesBuffer, int32_t* bufferSize);
const ErrorCode CatchDifficultyCalculator_CalculateTimedLazy(ManagedObjectHandle calcHandle, ManagedObjectHandle modsHandle, ManagedObjectHandle* timedAttributesEnumeratorHandle);
const ErrorCode CatchDifficultyCalculator_CalculateTimedLazy_Next(ManagedObjectHandle enumeratorHandle, NativeTimedCatchDifficultyAttributes* obj);
const ErrorCode CatchDifficultyCalculator_CalculateTimedLazy_Destroy(ManagedObjectHandle enumeratorHandle);
const ErrorCode CatchDifficultyCalculator_Destroy(ManagedObjectHandle handle);
const ErrorCode ManiaDifficultyCalculator_Create(ManagedObjectHandle rulesetHandle, ManagedObjectHandle beatmapHandle, NativeManiaDifficultyCalculator* nativeManiaDifficultyCalculatorPtr);
const ErrorCode ManiaDifficultyCalculator_Calculate(ManagedObjectHandle calcHandle, ManagedObjectHandle modsHandle, NativeManiaDifficultyAttributes* nativeAttributesPtr);
const ErrorCode ManiaDifficultyCalculator_CalculateTimed(ManagedObjectHandle calcHandle, ManagedObjectHandle modsHandle, NativeTimedManiaDifficultyAttributes* nativeTimedAttributesBuffer, int32_t* bufferSize);
const ErrorCode ManiaDifficultyCalculator_CalculateTimedLazy(ManagedObjectHandle calcHandle, ManagedObjectHandle modsHandle, ManagedObjectHandle* timedAttributesEnumeratorHandle);
const ErrorCode ManiaDifficultyCalculator_CalculateTimedLazy_Next(ManagedObjectHandle enumeratorHandle, NativeTimedManiaDifficultyAttributes* obj);
const ErrorCode ManiaDifficultyCalculator_CalculateTimedLazy_Destroy(ManagedObjectHandle enumeratorHandle);
const ErrorCode ManiaDifficultyCalculator_Destroy(ManagedObjectHandle handle);
const ErrorCode OsuDifficultyCalculator_Create(ManagedObjectHandle rulesetHandle, ManagedObjectHandle beatmapHandle, NativeOsuDifficultyCalculator* nativeOsuDifficultyCalculatorPtr);
const ErrorCode OsuDifficultyCalculator_Calculate(ManagedObjectHandle calcHandle, ManagedObjectHandle modsHandle, NativeOsuDifficultyAttributes* nativeAttributesPtr);
const ErrorCode OsuDifficultyCalculator_CalculateTimed(ManagedObjectHandle calcHandle, ManagedObjectHandle modsHandle, NativeTimedOsuDifficultyAttributes* nativeTimedAttributesBuffer, int32_t* bufferSize);
const ErrorCode OsuDifficultyCalculator_CalculateTimedLazy(ManagedObjectHandle calcHandle, ManagedObjectHandle modsHandle, ManagedObjectHandle* timedAttributesEnumeratorHandle);
const ErrorCode OsuDifficultyCalculator_CalculateTimedLazy_Next(ManagedObjectHandle enumeratorHandle, NativeTimedOsuDifficultyAttributes* obj);
const ErrorCode OsuDifficultyCalculator_CalculateTimedLazy_Destroy(ManagedObjectHandle enumeratorHandle);
const ErrorCode OsuDifficultyCalculator_Destroy(ManagedObjectHandle handle);
const ErrorCode TaikoDifficultyCalculator_Create(ManagedObjectHandle rulesetHandle, ManagedObjectHandle beatmapHandle, NativeTaikoDifficultyCalculator* nativeTaikoDifficultyCalculatorPtr);
const ErrorCode TaikoDifficultyCalculator_Calculate(ManagedObjectHandle calcHandle, ManagedObjectHandle modsHandle, NativeTaikoDifficultyAttributes* nativeAttributesPtr);
const ErrorCode TaikoDifficultyCalculator_CalculateTimed(ManagedObjectHandle calcHandle, ManagedObjectHandle modsHandle, NativeTimedTaikoDifficultyAttributes* nativeTimedAttributesBuffer, int32_t* bufferSize);
const ErrorCode TaikoDifficultyCalculator_CalculateTimedLazy(ManagedObjectHandle calcHandle, ManagedObjectHandle modsHandle, ManagedObjectHandle* timedAttributesEnumeratorHandle);
const ErrorCode TaikoDifficultyCalculator_CalculateTimedLazy_Next(ManagedObjectHandle enumeratorHandle, NativeTimedTaikoDifficultyAttributes* obj);
const ErrorCode TaikoDifficultyCalculator_CalculateTimedLazy_Destroy(ManagedObjectHandle enumeratorHandle);
const ErrorCode TaikoDifficultyCalculator_Destroy(ManagedObjectHandle handle);
}
