name: Deploy

on:
  workflow_dispatch:
    inputs:
      branch_name:
        description: "tosuapp/osu branch name"
        required: false
        type: string

      publish_napi:
        description: "Publish osu-native-napi?"
        required: false
        type: boolean
        default: false

      publish_wrapper:
        description: "Publish osu-native-wrapper?"
        required: false
        type: boolean
        default: false

permissions:
  contents: read
  id-token: write

jobs:
  publish:
    needs: build
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22.22.0"
          registry-url: 'https://registry.npmjs.org'

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: "10.33.0"

      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          pattern: osu-native-*
          path: ./downloads

      - name: Bump versions
        if: ${{ inputs.branch_name != '' }}
        shell: bash
        run: |
          PR_SHA8="$(git -C "$GITHUB_WORKSPACE/.work/osu-native/osu.Game" rev-parse --short=8 HEAD)"
          PR_VERSION_SUFFIX="${BRANCH_NAME}.${PR_SHA8}"

          cd $GITHUB_WORKSPACE/packages/cpp-binding
          BASE_BINDING_VERSION="$(node -p "require('./package.json').version")"
          NEW_BINDING_VERSION="${BASE_BINDING_VERSION}-${PR_VERSION_SUFFIX}"
          npm version "$NEW_BINDING_VERSION" --no-git-tag-version

          cd $GITHUB_WORKSPACE/packages/wrapper
          BASE_WRAPPER_VERSION="$(node -p "require('./package.json').version")"
          NEW_WRAPPER_VERSION="${BASE_WRAPPER_VERSION}-${PR_VERSION_SUFFIX}"
          npm version "$NEW_WRAPPER_VERSION" --no-git-tag-version
          npm pkg set "dependencies.@tosuapp/osu-native-napi=$NEW_BINDING_VERSION"

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Copy dll files
        if: ${{ inputs.publish_napi == true }}
        shell: bash
        run: |
          cd $GITHUB_WORKSPACE
          mkdir -p packages/cpp-binding/dist

          cp -rf ./downloads/osu-native-windows-x64/* packages/cpp-binding/dist/
          cp -rf ./downloads/osu-native-linux-x64/* packages/cpp-binding/dist/

      - name: Build Wrapper
        if: ${{ inputs.publish_wrapper == true }}
        shell: bash
        run: |
          cd $GITHUB_WORKSPACE/packages/wrapper
          pnpm build

      - name: Publish binding
        if: ${{ inputs.publish_napi == true }}
        shell: bash
        env:
          NPM_CONFIG_PROVENANCE: true
        run: |
          cd $GITHUB_WORKSPACE/packages/cpp-binding
          if [ -n "$BRANCH_NAME" ]; then
            npm publish --access public --provenance --tag=dev
          else
            npm publish --access public --provenance
          fi

      - name: Publish wrapper
        if: ${{ inputs.publish_wrapper == true }}
        shell: bash
        env:
          NPM_CONFIG_PROVENANCE: true
        run: |
          cd $GITHUB_WORKSPACE/packages/wrapper
          if [ -n "$BRANCH_NAME" ]; then
            npm publish --access public --provenance --tag=dev
          else
            npm publish --access public --provenance
          fi


  build:
    runs-on: ${{ matrix.runner }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: windows-x64
            runner: windows-latest
            platform: win-x64
            extension: .dll

          - name: linux-x64
            runner: ubuntu-latest
            platform: linux-x64
            extension: .so

    env:
      BRANCH_NAME: ${{ inputs.branch_name }}
      PLATFORM: ${{ matrix.platform }}
      EXTENSION: ${{ matrix.extension }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        if: ${{ inputs.publish_napi == true }}
        uses: actions/setup-node@v4
        with:
          node-version: "22.22.0"
          registry-url: "https://registry.npmjs.org"

      - name: Setup pnpm
        if: ${{ inputs.publish_napi == true }}
        uses: pnpm/action-setup@v4
        with:
          version: "10.33.0"

      - name: Checkout osu-native
        if: ${{ inputs.publish_napi == true }}
        uses: actions/checkout@v4
        with:
          repository: tosuapp/osu-native
          path: .work/osu-native
          fetch-depth: 1
          submodules: recursive

      - name: Checkout osu PR branch
        if: ${{ inputs.branch_name != '' && inputs.publish_napi == true }}
        shell: bash
        run: |
          cd .work/osu-native/osu.Game
          git fetch origin "${BRANCH_NAME}:${BRANCH_NAME}"
          git checkout "${BRANCH_NAME}"

      - name: Setup .NET
        if: ${{ inputs.publish_napi == true }}
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "10.0.x"

      - name: Build osu-native (${{ matrix.name }})
        if: ${{ inputs.publish_napi == true }}
        shell: bash
        run: |
          cd "$GITHUB_WORKSPACE"
          dotnet publish ".work/osu-native/osu.Native/osu.Native.csproj" -c Release -r "${PLATFORM}" -o .native-artifacts

      - name: Copy osu.Native${{ matrix.extension }}
        if: ${{ inputs.publish_napi == true }}
        shell: bash
        run: |
          cd "$GITHUB_WORKSPACE"
          cp ".native-artifacts/osu.Native${EXTENSION}" "packages/cpp-binding/osu.Native${EXTENSION}"
          ls -la "packages/cpp-binding"

      - name: Install dependencies
        if: ${{ inputs.publish_napi == true }}
        shell: bash
        run: |
          pnpm install --frozen-lockfile

      - name: Build binding package
        if: ${{ inputs.publish_napi == true }}
        shell: bash
        run: |
          cd "$GITHUB_WORKSPACE/packages/cpp-binding"
          pnpm build

          ls -la

      - name: Upload artifact
        if: ${{ inputs.publish_napi == true }}
        uses: actions/upload-artifact@v4
        with:
          name: osu-native-${{ matrix.name }}
          path: packages/cpp-binding/dist/
          retention-days: 1
          if-no-files-found: error